// next-seo.config.js
export default {
  titleTemplate: "%s – DivineShop",
  defaultTitle: "DivineShop | Shop tài khoản tự động, uy tín",
  description:
    "DivineShop phân phối tài khoản game, ứng dụng, dịch vụ… giá tốt, giao tự động, hỗ trợ 24/7.",

  additionalMetaTags: [
    {
      property: "og:image",
      content:
        "https://divineshop.vn/image/catalog/Anh/14.03.2022/Image%202022-07-03-1656817479-97266.png?hash=1656817567",
      keyOverride: "og:image",
      "data-react-helmet": "true",
    },
    {
      name: "sitemap",
      content: "https://shop-divine.vercel.app/sitemap.xml",
    },
    {
      name: "keywords",
      content: [
        "DivineShop",
        "divine shop",
        "divineshop.vn",
        "mua tài khoản game giá rẻ",
        "tài khoản Shopee chính chủ",
        "tài khoản Facebook vĩnh viễn",
        "shop tài khoản tự động uy tín",
        "bán tài khoản trực tuyến nhanh chóng",
        "đăng ký tài khoản ứng dụng",
        "tài khoản game online giá rẻ",
        "tài khoản Zing MP3 VIP",
        "tài khoản Netflix Premium",
        "tài khoản Spotify Family giá tốt",
        "tài khoản Canva Pro tự động",
        "tài khoản Microsoft Office 365",
        "tài khoản Adobe Creative Cloud",
        "tài khoản Google Drive dung lượng lớn",
        "tài khoản Steam giá rẻ",
        "tài khoản Garena Free Fire",
        "tài khoản Liên Quân Mobile",
        "mua bán trao đổi tài khoản trực tuyến",
        "dịch vụ mua tài khoản nhanh chóng",
        "mua game bản quyền",
        "mua phần mềm bản quyền",
        "steam wallet",
        "mua steam wallet",
        "mua key steam",
        "mua game steam",
        "mua game giá rẻ",
        "tài khoản steam offline",
        "steam account",
        "mua cd key game",
        "mua gift card steam",
        "mua game bản quyền việt nam",
        "game bản quyền giá rẻ",
        "game pc giá rẻ",
        "game pc bản quyền",
        "mua key game bản quyền",
        "key game giá rẻ",
        "adobe bản quyền",
        "mua adobe bản quyền",
        "photoshop bản quyền",
        "illustrator bản quyền",
        "premiere pro bản quyền",
        "after effects bản quyền",
        "adobe creative cloud bản quyền",
        "mua adobe giá rẻ",
        "mua adobe cc giá rẻ",
        "microsoft office bản quyền",
        "office 365 bản quyền",
        "mua office giá rẻ",
        "mua windows bản quyền",
        "windows 10 bản quyền",
        "windows 11 bản quyền",
        "mua key win bản quyền",
        "mua key win giá rẻ",
        "netflix giá rẻ",
        "netflix premium giá rẻ",
        "spotify premium",
        "mua spotify premium",
        "tài khoản spotify",
        "autodesk bản quyền",
        "mua autodesk",
        "autocad bản quyền",
        "3ds max bản quyền",
        "revit bản quyền",
        "udemy giá rẻ",
        "mua khóa học udemy",
        "học online giá rẻ",
        "khóa học photoshop",
        "khóa học illustrator",
        "khóa học premiere",
        "khóa học after effects",
        "học thiết kế đồ họa",
        "học edit video",
        "phần mềm học tập giá rẻ",
        "phần mềm thiết kế giá rẻ",
        "full app bản quyền",
        "ứng dụng bản quyền",
        "phần mềm tiện ích",
        "phần mềm bảo mật",
        "phần mềm vpn",
        "game fps bản quyền",
        "game rpg bản quyền",
        "game open world bản quyền",
        "game sinh tồn bản quyền",
        "game indie bản quyền",
        "game mô phỏng bản quyền",
        "game chiến thuật bản quyền",
        "co-op game bản quyền",
        "pvp game bản quyền",
        "pve game bản quyền",
        "sandbox game bản quyền",
        "gift card game",
        "mua gift card giá rẻ",
        "thẻ nạp game bản quyền",
        "thẻ gift card",
        "thẻ game steam",
        "sale divine shop",
        "flash sale divine shop",
        "giảm giá divine shop",
        "khuyến mãi divine shop",
        "divine esports",
        "đội divine esports",
        "merchandise divine esports",
        "quà tặng game thủ",
        "quà lưu niệm esports",
        "mua áo esports",
        "mua đồ divine esports",
        "cộng đồng game thủ divine",
        "cộng đồng pubg divine",
        "giải đấu pubg divine",
        "pubg bản quyền",
        "mua pubg bản quyền",
        "pubg giá rẻ",
        "pubg steam",
        "pubg gift card",
        "game bản quyền uy tín",
        "game bản quyền nhanh",
        "tải game bản quyền",
        "tải phần mềm bản quyền",
        "mua phần mềm online",
        "thanh toán game bản quyền",
        "thanh toán phần mềm bản quyền",
        "hỗ trợ mua game",
        "hướng dẫn mua phần mềm",
        "hướng dẫn mua game",
        "bảo hành game bản quyền",
        "bảo hành phần mềm bản quyền",
        "chính sách hoàn tiền divine",
        "chính sách bảo mật divine",
        "điều khoản dịch vụ divine",
        "liên hệ divine shop",
        "hotline divine shop",
        "hỗ trợ khách hàng divine",
        "chăm sóc khách hàng divine",
        "zalo divine shop",
        "fanpage divine shop",
        "divine shop uy tín không",
        "review divine shop",
        "đánh giá divine shop",
        "mua game bản quyền ở đâu uy tín",
        "mua phần mềm bản quyền ở đâu uy tín",
        "divine shop có lừa đảo không",
        "divine shop có uy tín không",
        "hướng dẫn kích hoạt key steam",
        "hướng dẫn kích hoạt key windows",
        "hướng dẫn kích hoạt adobe",
        "hướng dẫn kích hoạt office",
        "hướng dẫn kích hoạt autodesk",
        "hướng dẫn kích hoạt spotify",
        "hướng dẫn kích hoạt netflix",
        "tải steam",
        "đăng ký steam",
        "đăng nhập steam",
        "tạo tài khoản steam",
        "cách mua game trên steam",
        "cách nạp tiền steam",
        "cách nạp steam wallet",
        "thanh toán paypal divine shop",
        "thanh toán momo divine shop",
        "thanh toán viettelpay divine shop",
        "thanh toán banking divine shop",
        "game sale divine",
        "game giảm giá steam",
        "phần mềm giảm giá divine",
        "mua key game nước ngoài",
        "chuyển vùng steam",
        "mua key game global",
        "mua key game us",
        "mua key game eu",
        "mua key game asia",
        "gift card google play",
        "gift card itunes",
        "gift card netflix",
        "gift card spotify",
        "gift card xbox",
        "gift card playstation",
        "playstation plus",
        "xbox game pass",
        "nintendo eshop",
        "thẻ nintendo eshop",
        "mua thẻ nintendo eshop",
        "mua game switch",
        "mua game nintendo switch",
        "phần mềm chỉnh sửa video bản quyền",
        "phần mềm chỉnh sửa ảnh bản quyền",
        "phần mềm dựng phim bản quyền",
        "phần mềm học online bản quyền",
        "khóa học online bản quyền",
        "khóa học lập trình giá rẻ",
        "khóa học marketing giá rẻ",
        "mua khóa học tiếng anh",
        "mua khóa học kỹ năng",
        "mua sách điện tử bản quyền",
        "ebook bản quyền",
        "tải ebook bản quyền",
        "đọc sách bản quyền",
        "học đồ họa online",
        "học photoshop online",
        "học premiere online",
        "học autocad online",
        "mua bản quyền autocad giá rẻ",
        "mua bản quyền 3ds max giá rẻ",
        "mua bản quyền revit giá rẻ",
        "phần mềm kiến trúc bản quyền",
        "phần mềm 3d bản quyền",
        "phần mềm mô phỏng bản quyền",
        "phần mềm kỹ thuật bản quyền"
      ].join(", "),
    },
    { name: "robots", content: "index,follow" },
    { name: "viewport", content: "width=device-width, initial-scale=1" },
    { name: "theme-color", content: "#2579f2" },
    { name: "author", content: "tungmmo (vtung15062005@gmail.com)" },
    { name: "revisit-after", content: "7 days" }
  ],

  canonical: "https://shop-divine.vercel.app/",

  openGraph: {
    type: "website",
    locale: "vi_VN",
    url: "https://shop-divine.vercel.app/",
    site_name: "DivineShop",
    images: [
      {
        url: "https://divineshop.vn/image/catalog/Anh/14.03.2022/Image%202022-07-03-1656817479-97266.png?hash=1656817567",
        width: 1200,
        height: 630,
        alt: "DivineShop thumbnail"
      }
    ]
  },

  twitter: {
    handle: "@divineshop",
    site: "@divineshop",
    cardType: "summary_large_image"
  },

  additionalLinkTags: [
    { rel: "icon", href: "/favicon.ico" },
    { rel: "apple-touch-icon", href: "/apple-touch-icon.png", sizes: "180x180" },
    { rel: "manifest", href: "/site.webmanifest" },
    { rel: "mask-icon", href: "/safari-pinned-tab.svg", color: "#f763cb" },
    { rel: "alternate", hrefLang: "vi", href: "https://shop-divine.vercel.app/" },
    { rel: "alternate", hrefLang: "en", href: "https://shop-divine.vercel.app/en" }
  ],

  additionalScriptTags: [
    {
      type: "application/ld+json",
      innerHTML: JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Organization",
        name: "DivineShop",
        url: "https://shop-divine.vercel.app/",
        logo: "https://shop-divine.vercel.app/favicon.ico",
        contactPoint: [
          {
            "@type": "ContactPoint",
            telephone: "+84-986-379-490",
            contactType: "Customer Service",
            areaServed: "VN",
            availableLanguage: ["Vietnamese", "English"]
          }
        ],
        email: "vtung15062005@gmail.com",
        sameAs: [
          "https://www.facebook.com/tungmmo05/?locale=vi_VN",
          "https://twitter.com/divineshop",
          "https://instagram.com/divineshop"
        ]
      })
    }
  ]
};
